id: P003286
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG13790
  title: རྒྱལ་སྲས་བསྟན་འཛིན་རབ་རྒྱས་ཀྱི་རྣམ་ཐར།
  author: ''
  volumes:
    a406a62a0cf64b4dbae459d5bea90dc4:
      image_group_id: I1KG15361
      title: ''
      volume_number: 1
      total_pages: 536
