id: P003286
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 10:52:45.323815
source_metadata:
  id: bdr:W1KG13790
  title: རྒྱལ་སྲས་བསྟན་འཛིན་རབ་རྒྱས་ཀྱི་རྣམ་ཐར།
  author: ''
  volumes:
    a406a62a0cf64b4dbae459d5bea90dc4:
      image_group_id: I1KG15361
      title: ''
      volume_number: 1
      total_pages: 536
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
